name: 'ListenBrainz Music Data'
description: 'Music listening data from ListenBrainz as JSON'
branding:
  icon: 'music'
  color: 'purple'

inputs:
  username:
    description: 'ListenBrainz username'
    required: true
  output_path:
    description: 'Path to write the JSON file'
    required: false
    default: 'src/data/music.json'
  stats_range:
    description: 'Time range for stats (this_week, this_month, this_year, week, month, quarter, half_yearly, all_time)'
    required: false
    default: 'this_month'
  top_count:
    description: 'Number of items in top lists'
    required: false
    default: '5'
  recent_count:
    description: 'Number of recent listens'
    required: false
    default: '5'
  commit_message:
    description: 'Git commit message for auto-commit'
    required: false
    default: 'chore: update listenbrainz data'
  skip_commit:
    description: 'Skip auto-commit (set to true to handle commits yourself)'
    required: false
    default: 'false'

outputs:
  changes_detected:
    description: 'Whether the output file changed (true/false)'
    value: ${{ steps.commit.outputs.changes_detected }}
  file_path:
    description: 'Repository-relative path to the output file'
    value: ${{ steps.commit.outputs.file_path }}

runs:
  using: 'composite'
  steps:
    - name: Fetch recent listens
      shell: bash
      run: bash ${{ github.action_path }}/scripts/fetch-listens.sh
      env:
        LB_USERNAME: ${{ inputs.username }}
        LB_RECENT_COUNT: ${{ inputs.recent_count }}
        LB_TMPDIR: ${{ runner.temp }}/listenbrainz-${{ github.run_id }}

    - name: Fetch stats
      shell: bash
      run: bash ${{ github.action_path }}/scripts/fetch-stats.sh
      env:
        LB_USERNAME: ${{ inputs.username }}
        LB_STATS_RANGE: ${{ inputs.stats_range }}
        LB_TOP_COUNT: ${{ inputs.top_count }}
        LB_TMPDIR: ${{ runner.temp }}/listenbrainz-${{ github.run_id }}

    - name: Build JSON
      shell: bash
      run: bash ${{ github.action_path }}/scripts/build-json.sh
      env:
        LB_USERNAME: ${{ inputs.username }}
        LB_STATS_RANGE: ${{ inputs.stats_range }}
        LB_OUTPUT_PATH: ${{ inputs.output_path }}
        LB_TMPDIR: ${{ runner.temp }}/listenbrainz-${{ github.run_id }}

    - name: Commit changes
      id: commit
      shell: bash
      run: bash ${{ github.action_path }}/scripts/commit-changes.sh
      env:
        LB_OUTPUT_PATH: ${{ inputs.output_path }}
        LB_COMMIT_MESSAGE: ${{ inputs.commit_message }}
        LB_SKIP_COMMIT: ${{ inputs.skip_commit }}

    - name: Cleanup
      if: always()
      shell: bash
      run: rm -rf "$LB_TMPDIR"
      env:
        LB_TMPDIR: ${{ runner.temp }}/listenbrainz-${{ github.run_id }}
